export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const CART_SAVE_SHIPPING_ADRESS = 'CART_SAVE_SHIPPING_ADRESS'

export const CART_SAVE_PAYEMENT_METHOD = 'CART_SAVE_PAYEMENT_METHOD'

export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'
