# Generated by Django 3.2.6 on 2022-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/tail.jpg', null=True, upload_to=''),
        ),
    ]
